### ISSUE TITLE
include Classes in docstring sections

### ISSUE THREAD

**Issue by fmv1992** [darkfeline/sphinxcontrib-napoleon#1]
Hi,

can you include Classes in your docstring sections?

According to PEP 257 they should be included in module level docstrings:

> The docstring for a module should generally list the classes, exceptions and functions (and any other objects) that are exported by the module, with a one-line summary of each.

Thank you.

**Comment by darkfeline** [comment]
This repository should probably be deleted, since it is a fork that fixes Python 3 compatibility, but since napolean has been merged into Sphinx, I suspect this has already been fixed upstream.
